Fix undefined reference to CHECK_FUNCTION_EXISTS.
On some systems, this macro is only defined when the appropriate module
is included explicitly. So do just that.

Other functions, such as CHECK_INCLUDE_FILES, are also available from
separate modules, but they are somehow included implicitly.

Problem reported by Rafael Belmonte.